### PR TITLE
#285: Fix: STACKREFLEN and QUEUEREFLEN is not aware of the deletion of key 

### LINKED ISSUE #285: `STACKREFLEN` is not aware of the deletion of key
I'm not sure the expected behavior of the STACKREF type, a ref behaves like a soft link to the key, that is, stackreflen report the correct len after trying to access a deleted key, which may be confusing.

**How to reproduce**
> m3/macos 14.2
> go run main.go based on commit `34d5fa5`
```
127.0.0.1:7379> set s1 1
OK
127.0.0.1:7379> stackrefpush st1 s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> del s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> stackrefpop st1
(nil)
127.0.0.1:7379> stackreflen st1
(integer) 0
```

**Expected behavior**

```
127.0.0.1:7379> set s1 1
OK
127.0.0.1:7379> stackrefpush st1 s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 1
127.0.0.1:7379> del s1
(integer) 1
127.0.0.1:7379> stackreflen st1
(integer) 0
127.0.0.1:7379> stackrefpop st1
(nil)
127.0.0.1:7379> stackreflen st1
(integer) 0
```

### PR DESCRIPTION
**Pull request by kushal0511-not**
closes #285.

- Added a maximum limit for the number of stacks and queues.
- Added a maximum limit for stack size and queue size.
- Cleanup will remove expired and deleted keys, and it will be called every time Length is called.
- Added tests for the above points.

### CODE REVIEW

File: core/queueref.go [hunk 1]
```diff
@@ -1,9 +1,21 @@
...
 )
 
+var (
+	MaxQueueSize = 10000
+	MaxQueues    = 1000
+)
+
+var (
+	QueueCount = 0
+	muQueue    sync.Mutex
```
Comment (JyotinderSingh) [inline core/queueref.go:16]: Why do we require a mutex?

File: core/queueref.go [hunk 2]
```diff
@@ -1,9 +1,21 @@
...
 import (
+	"errors"
+	"sync"
 	"unsafe"
 )
 
+var (
+	MaxQueueSize = 10000
+	MaxQueues    = 1000
+)
```
Comment (JyotinderSingh) [inline core/queueref.go:12]: These should be a part of the config instead of being global variables.

File: core/stackref.go [hunk 3]
```diff
@@ -81,3 +111,29 @@ func (s *StackRef) DeepCopy() *StackRef {
...
+func (s *StackRef) StackRefCleanup(store *Store) {
+	var validElements []int64
+
+	for {
+		val, err := s.si.Pop()
+		if err != nil {
+			break // Break the loop if the stack is empty
+		}
+
+		key := *((*string)(unsafe.Pointer(uintptr(val))))
```
Comment (JyotinderSingh) [inline core/stackref.go:129]: Rebase on the latest master please, we no longer use unsafe pointers in the codebase.

**Review by JyotinderSingh — CHANGES_REQUESTED** [review]

File: core/queueref.go (hunk 1 above)
Comment (kushal0511-not) [reply core/queueref.go:16]: Since it's a global variable, multiple clients trying to create new stacks concurrently will lead to thread safety issues.

File: core/queueref.go (hunk 2 above)
Comment (kushal0511-not) [reply core/queueref.go]: Done.

File: core/stackref.go (hunk 3 above)
Comment (kushal0511-not) [reply core/stackref.go:127]: done.

File: core/queueref.go (hunk 1 above)
Comment (soumya-codes) [reply core/queueref.go:13]: If these values are not being mutated there will not be any thread safety issues.
We can declare these variables as constants instead to guarantee immutability.

Comment (kushal0511-not) [reply core/queueref.go:13]: we will increment it when new stack is created.

Comment (soumya-codes) [reply core/queueref.go:13]: But obvious, so silly of me! Can we then just lock the critical part then?
```suggestion
	muQueue.Lock()
	QueueCount++
	muQueue.Unlock()	
```

Comment (kushal0511-not) [reply core/queueref.go:13]: yeah sure.

Comment (kushal0511-not) [reply core/queueref.go:13]: Done

**Review by soumya-codes — COMMENTED** [review]
Thanks for raising the PR @kushal0511-not . I have left a few minor comments and a request. Please let me know if you see any concerns.

File: config/main.go [hunk 4]
```diff
@@ -27,3 +27,13 @@ var (
...
 	RequirePass string = constants.EmptyStr
 )
+
+var (
+	MaxQueueSize = 10000
+	MaxQueues    = 1000
+)
+
+var (
+	MaxStackSize = 10000
```
[the remark this answers is not in the document]
Comment (kushal0511-not) [reply config/main.go]: yes sure
only **maxStacks** needs to be variable because i need to set it higher for benchmark.
others i have changed it to const.

File: core/eval.go [hunk 5]
```diff
@@ -1110,8 +1110,12 @@ func evalQREFINS(args []string, store *Store) []byte {
 	}
 
 	obj := store.Get(args[0])
+	qr, err := NewQueueRef()
+	if err != nil {
+		return Encode(err, false)
```
[the remark this answers is not in the document]
Comment (kushal0511-not) [reply core/eval.go:1115]: Done.

File: core/queueref.go [hunk 6]
```diff
@@ -82,6 +100,32 @@ func (q *QueueRef) DeepCopy() *QueueRef {
...
+// remains efficient without degrading system performance
+func (q *QueueRef) QueueRefCleanup(store *Store) {
+	var validElements []int64
+	for {
+		val, err := q.qi.Remove()
+		if err != nil {
+			break // Break the loop if the queue is empty
+		}
+
+		key := *((*string)(unsafe.Pointer(uintptr(val))))
```
[the remark this answers is not in the document]
Comment (kushal0511-not) [reply core/queueref.go:125]: yeah sure i will open an issue.

[the remark this answers is not in the document]
Comment (kushal0511-not) [reply core/queueref.go:125]: created issue
https://github.com/DiceDB/dice/issues/407

File: config/main.go [hunk 7]
```diff
@@ -27,3 +27,5 @@ var (
 	// If requirepass is set to an empty string, no authentication is required
 	RequirePass string = constants.EmptyStr
 )
+
+var MaxStacks = 1000
```
Comment (soumya-codes) [inline config/main.go:31]: Even if this is a global variable, lets move it to its specific file.

File: config/main.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (soumya-codes) [reply config/main.go]: If maxStacks would never exceed a value, may be needn't benchmark it beyond that value. @JyotinderSingh wdyt?

[the remark this answers is not in the document]
Comment (kushal0511-not) [reply config/main.go]: @soumya-codes Sorry , I just saw that benchmark was for Pop() operation so we can not need to create stacks for that so removing from there and made it contsant.

File: core/queueref.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (soumya-codes) [reply core/queueref.go:125]: Thanks

**Review by JyotinderSingh — COMMENTED** [review]
Thanks for these changes @kushal0511-not. Thanks for the reviews @soumya-codes.

Merging.

**Review by JyotinderSingh — APPROVED** [review]
