### PR TITLE
Server doesn't crash if Obj Type is not present and float support in GET Command

### LINKED ISSUE #1697: Inconsistent `{GET}`: GET on HSET crashes DiceDB server
## Steps to reproduce
```bash
HSET map k1 v1
GET map
```

## Expected output

The expected output when the above set of commands

```
invalid op
```

## Observed output
Server crashes

```
2025-04-18 19:38:20 panic: unknown object type ssmap
2025-04-18 19:38:20 
2025-04-18 19:38:20 goroutine 19 [running]:
2025-04-18 19:38:20 github.com/dicedb/dice/internal/cmd.getWireValueFromObj(0xc0003f80a0?)
2025-04-18 19:38:20     /src/internal/cmd/cmd_get.go:91 +0x194
2025-04-18 19:38:20 github.com/dicedb/dice/internal/cmd.newGETRes(...)
2025-04-18 19:38:20     /src/internal/cmd/cmd_get.go:48
2025-04-18 19:38:20 github.com/dicedb/dice/internal/cmd.evalGET(0xc0001a40e0?, 0xc000422013?)
2025-04-18 19:38:20     /src/internal/cmd/cmd_get.go:67 +0x4a
2025-04-18 19:38:20 github.com/dicedb/dice/internal/cmd.executeGET(0xc000426000, 0xc0000250e0?)
2025-04-18 19:38:20     /src/internal/cmd/cmd_get.go:75 +0x7d
2025-04-18 19:38:20 github.com/dicedb/dice/internal/cmd.(*Cmd).Execute(0xc000426000, 0xc0001a40e0)
2025-04-18 19:38:20     /src/internal/cmd/cmds.go:60 +0x143
```

### PR DESCRIPTION
**Pull request by Abhijeetsng97**
Server doesn't crash if Obj Type is not present and float support in GET Command
fixes #1697 #1698

### CODE REVIEW

File: internal/cmd/cmd_get.go [hunk 1]
```diff
@@ -38,22 +38,26 @@ func init() {
 	CommandRegistry.AddCommand(cGET)
 }
 
-func newGETRes(obj *object.Obj) *CmdRes {
+func newGETRes(obj *object.Obj) (*CmdRes, error) {
```
Comment (arpitbbhayani) [inline internal/cmd/cmd_get.go:41]: We do not want to return `error` from this function. Create a CmdRes object instead.

**Comment by arpitbbhayani** [comment]
Thanks for the patch!
