### PR TITLE
#1036 Preserve TTL after APPEND command

### LINKED ISSUE #1036: Inconsistent `APPEND`: APPEND command incorrectly resets TTL to -1
## Description

In DiceDB, the APPEND command is currently resetting the TTL (Time to Live) of a key to -1 (no expiration) instead of preserving the existing TTL. This behavior is inconsistent with Redis, where the APPEND command does not affect the TTL of a key.

When a key with a set TTL is modified using APPEND, the TTL should continue counting down as expected, without being reset. However, in DiceDB, the TTL is being removed entirely, resulting in the key remaining indefinitely.

## Impact
This issue may lead to unintended key persistence when using the APPEND command on keys that are expected to expire. It affects applications that rely on key expiration for cache management, session handling, or other use cases involving TTLs.

## Steps to reproduce

- Start DiceDB on port 7379.
- Run the following commands using `redis-cli` or 'dicedb-cli':
```
SET key "Hello" EX 20    # Set a key with a value and a 20-second TTL
APPEND key "World"       # Append to the value
TTL key                  # Check the TTL after append
```

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```
127.0.0.1:7379> SET key "Hello" EX 20
OK
127.0.0.1:7379> APPEND key "World"
(integer) 10
127.0.0.1:7379> TTL key
(integer) 16
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
127.0.0.1:7379> SET key "Hello" EX 20
OK
127.0.0.1:7379> APPEND key "World"
(integer) 10
127.0.0.1:7379> TTL key
(integer) -1   # TTL is incorrectly reset to -1 (no expiration)
```

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. Changes in the [dice](https://github.com/dicedb/dice) code to meet the expected behavior where the TTL is preserved after the APPEND operation.
2. Addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

### PR DESCRIPTION
**Pull request by dankot12**
- Resolved an issue where the TTL was incorrectly reset to -1 after using the APPEND command on a key with an existing TTL.
- The TTL is now correctly preserved after appending to a key, matching expected behavior in Redis.
- Added relevant test cases to ensure that TTL is maintained across APPEND operations.
- Tests include scenarios for key expiration after APPEND and correct TTL decrement over time.

## Benchmark
image

Closes #1036

### CODE REVIEW

File: internal/eval/eval.go
Comment (apoorvyadav1111) [inline internal/eval/eval.go:1]: Hi, I think we should be able to reuse the logic for this function for both cases as follows:
```go

	if obj == nil {
		obj = store.NewObj("", -1, object.ObjTypeString, object.ObjEncodingRaw)
		store.Put(key, obj)
	}

	_, currentEnc := object.ExtractTypeEncoding(obj)

	var currentValueStr string
	switch currentEnc {
	case object.ObjEncodingInt:
		// If the encoding is an integer, convert the current value to a string for concatenation
		currentValueStr = strconv.FormatInt(obj.Value.(int64), 10)
	case object.ObjEncodingEmbStr, object.ObjEncodingRaw:
		// If the encoding is a string, retrieve the string value for concatenation
		currentValueStr = obj.Value.(string)
	default:
		// If the encoding is neither integer nor string, return a "wrong type" error
		return diceerrors.NewErrWithFormattedMessage(diceerrors.WrongTypeErr)
	}

	obj.Value = currentValueStr + value
	obj.TypeEncoding = object.ObjTypeString | object.ObjEncodingRaw

```

I have ran this locally and all the tests were passing. If you prefer to make it more modular, please go ahead. Perhaps a function in the store can be used to update the object and encoding.

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]

File: internal/eval/eval.go
Comment (dankot12) [reply internal/eval/eval.go:1]: Hi @apoorvyadav1111, thanks for your review. Let me work on this.

In the meanwhile, can you assign this PR to me?

Comment (dankot12) [reply internal/eval/eval.go:1]: Hi @apoorvyadav1111 , I had a look at your suggestion. Unfortunately, the logic cannot be reused. The switch case when the key doesn't exist mainly tries to convert the value either as a string or an integer for its efficient storage in DiceDB.

The switch case used when the key exists and the value needs to be appended tries to transform the existing value into a string (string remains as string and int is converted to string).

I have taken this logic out of the code into its own separate functions as it could be used by other features of DiceDB.

File: integration_tests/commands/async/append_test.go
Comment (apoorvyadav1111) [inline integration_tests/commands/async/append_test.go:1]: Hi, I know this was not part of the issue but would it be okay for you to migrate from `"gotest.tools/v3/assert"` to `github.com/stretchr/testify/assert` as this is a standard moving forward

File: internal/eval/eval.go
Comment (apoorvyadav1111) [reply internal/eval/eval.go:1]: Thank you for considering my suggestion and spending time on it. We will move ahead with your approach.

File: internal/store/store.go [hunk 1]
```diff
@@ -268,6 +268,15 @@ func (store *Store) GetDel(k string, opts ...DelOption) *object.Obj {
 	return v
 }
 
+// GetUnixTimeExpiry returns the expiry time for an object.
+func (store *Store) GetUnixTimeExpiry(obj *object.Obj) (uint64, bool) {
```
Comment (apoorvyadav1111) [inline internal/store/store.go:272]: we have a function already created for this: GetExpiry() from expiry.go. Please try to reuse that function as all other evals use this.

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]
Hi, thanks for the changes and finding the bug and its fix. However merging this PR will have to blocked until #1095 is merged as the code is being migrated and to avoid any fix being lost in the process.

**Comment by apoorvyadav1111** [comment]
Hi @dankot12 , please rebase you branch with the latest changes with the migrated eval function. Please reach out to me if you need any clarifications.

**Comment by apoorvyadav1111** [comment]
Hi @dankot12 , Hope you are well. I am eager to know more about progress on this issue. Please contact me or anyone on the discord community if you are blocked. 

Thanks.

**Comment by lucifercr07** [comment]
@dankot12 please resolve conflicts. https://github.com/DiceDB/dice/pull/1095 is merged now so please fix according to the migrated command.

**Comment by dankot12** [comment]
Hi @lucifercr07, will do this by EOD Eastern Time. Thanks

**Comment by dankot12** [comment]
Hi @lucifercr07 @apoorvyadav1111, this PR is ready for your review. Thanks!

File: internal/eval/store_eval.go [hunk 2]
```diff
@@ -814,66 +814,61 @@ func evalAPPEND(args []string, store *dstore.Store) *EvalResponse {
...
-	newValue := currentValueStr + value
-
-	store.Put(key, store.NewObj(newValue, -1, object.ObjTypeString, object.ObjEncodingRaw))
+	// Append the value
+	newValue := currentValue + value
 
+	// We need to store the new appended value as a string
+	// Even if append is performed on integers, the result will be stored as a string
+	// This is consistent with the redis implementation as append is considered a string operation
+	store.Put(key, store.NewObj(newValue, exDurationMs, object.ObjTypeString, object.ObjEncodingRaw))
```
Comment (apoorvyadav1111) [inline internal/eval/store_eval.go:871]: Maybe this could work
```suggestion
	newValue := currentValue + value
        obj.Value = newValue
```

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]
Hi, thanks for the changes, left some comments.

**Comment by apoorvyadav1111** [comment]
Hi @dankot12 , Hope you are well. I am eager to know more about progress on this issue. Please contact me or anyone on the discord community if you are blocked.

Thanks.

**Comment by arpitbbhayani** [comment]
@dankot12 any updates?

**Comment by dankot12** [comment]
Hi @apoorvyadav1111 @arpitbbhayani, will be working on this today. Thanks.

File: internal/eval/store_eval.go (hunk 2 above)
Comment (dankot12) [reply internal/eval/store_eval.go:871]: Hi @apoorvyadav1111 , this doesn't work. When we append a key which is stored as a number (int/float/etc.) type, an APPEND operation should ideally convert the stored value into a string.

For example, if I do the following:

```
SET key 1
APPEND key 2
GET key
```

The key should be returned as a string and not a `number` type. because `APPEND` is a string operation here.

---
If we just do the following:
```
newValue := currentValue + value
obj.Value = newValue
```
we do not convert the object type from `number` type to `string` type, but preserve the current type.

File: integration_tests/commands/async/append_test.go
[the remark this answers is not in the document]
Comment (dankot12) [reply integration_tests/commands/async/append_test.go:1]: Done

**Comment by dankot12** [comment]
Hi @apoorvyadav1111, the PR is ready for your review.

**Comment by apoorvyadav1111** [comment]
Hi, @dankot12 , please fix the lint errors.

**Review by apoorvyadav1111 — CHANGES_REQUESTED** [review]
need lint errors fix

**Review by apoorvyadav1111 — APPROVED** [review]
