### PR TITLE
Del, Exists, Get command test cases

### LINKED ISSUE #1484: IronHawk Integration Tests: DEL
We reimplemented the core of the DiceDB engine and re-wrote - the wire protocol, execution engine, and config management. This rewrite helped us gain 32% throughput over our existing benchmark.

To make DiceDB stable even after 100s of changes, we have to put effort
into making sure we have a comprehensive integration test suite for each command. This issue will be used to cover the port and fixes for integration tests related to the command `DEL`.

Here are the pre-requisite

1. setup DiceDB server locally from the source - [instructions](https://github.com/dicedb/dice)
2. setup DiceDB Go SDK locally from the source - [instructions](https://github.com/dicedb/dicedb-go)
3. refer to the `Pointing to local checked-out `dicedb-go` section in `README`.

### Start the DiceDB server with IronHawk engine

```
$ go run main.go --engine ironhawk --log-level debug
```

## Setting up Integration Tests

0. Make sure the DiceDB server is running. This is essential for you to run the tests
1. Integration tests of all the commands can be found under `tests/commands/ironhawk` with the name `del_test.go`.
2. For the command `DEL` find the tests
3. Run the test function using the following command

```
$ TEST_FUNC=^TestSet$ make test-one
```

Replace the name of the function with whatever the name is in your `del_test.go` file.
Note the `^` and `$` in the `TEST_FUNC` variable. It is a regex and this way, the command
executes only one function which is `TestSet`.

## Things need to be done

1. Fix any dependency error (refer `set_test.go` file)
2. Fix any execution error (refer `set_test.go` file)
3. There are some utility functions written, use them, but as per the `set_test.go` file.

Ideally, all the tests should pass. If some are failing

1. either fix them (if you think it is a bug in the tests)
2. or raise a bug if you think there is an implementation mistake

Eventually, we need 100% integration test coverage for all the commands to
prove that DiceDB is stable and production-ready.

If you find any other bug while you are implementing it, you can either

1. fix it yourself and submit it in a new PR
2. raise a [GitHub issue](https://github.com/DiceDB/dice/issues)

## Follow the contribution guidelines

These are general guidelines to follow before you submit a patch. Please mark them as done
once you complete them

- [ ] please go through the [CONTRIBUTING](https://github.com/DiceDB/dice/tree/master/CONTRIBUTING) guide
- [ ] follow [LOGGING best practices](https://github.com/DiceDB/dice/blob/master/CONTRIBUTING/logging.md)
- [ ] follow [Golang best practices](https://github.com/DiceDB/dice/blob/master/CONTRIBUTING/go.md)
- [ ] run `make lint` on your local copy of the codebase

### PR DESCRIPTION
**Pull request by Abhijeetsng97**
fixes #1484 & #1486  &  #1490 as per new flow

```

CGO_ENABLED=1 go test -v -race -count=1 --run ^TestEXPIRE$ ./tests/...
=== RUN   TestEXPIRE
=== RUN   TestEXPIRE/Set_with_EXPIRE_command
=== RUN   TestEXPIRE/Check_if_key_is_nil_after_expiration
=== RUN   TestEXPIRE/EXPIRE_non-existent_key
=== RUN   TestEXPIRE/EXPIRE_with_past_time
=== RUN   TestEXPIRE/EXPIRE_with_invalid_syntax
=== RUN   TestEXPIRE/Test(NX):_Set_the_expiration_only_if_the_key_has_no_expiration_time
=== RUN   TestEXPIRE/Test(XX):_Set_the_expiration_only_if_the_key_already_has_an_expiration_time
=== RUN   TestEXPIRE/TEST(GT):_Set_the_expiration_only_if_the_new_expiration_time_is_greater_than_the_current_one
=== RUN   TestEXPIRE/TEST(LT):_Set_the_expiration_only_if_the_new_expiration_time_is_less_than_the_current_one
=== RUN   TestEXPIRE/TEST(LT):_Set_the_expiration_only_if_the_new_expiration_time_is_less_than_the_current_one#01
=== RUN   TestEXPIRE/TEST(NX_+_LT/GT)
=== RUN   TestEXPIRE/TEST(XX_+_LT/GT)
=== RUN   TestEXPIRE/Test_if_value_is_nil_after_expiration
=== RUN   TestEXPIRE/Test_if_value_is_nil_after_expiration#01
=== RUN   TestEXPIRE/Invalid_Command_Test
=== RUN   TestEXPIRE/EXPIRE_with_no_keys_or_arguments
--- PASS: TestEXPIRE (6.02s)
    --- PASS: TestEXPIRE/Set_with_EXPIRE_command (0.00s)
    --- PASS: TestEXPIRE/Check_if_key_is_nil_after_expiration (2.00s)
    --- PASS: TestEXPIRE/EXPIRE_non-existent_key (0.00s)
    --- PASS: TestEXPIRE/EXPIRE_with_past_time (0.00s)
    --- PASS: TestEXPIRE/EXPIRE_with_invalid_syntax (0.00s)
    --- PASS: TestEXPIRE/Test(NX):_Set_the_expiration_only_if_the_key_has_no_expiration_time (0.00s)
    --- PASS: TestEXPIRE/Test(XX):_Set_the_expiration_only_if_the_key_already_has_an_expiration_time (0.00s)
    --- PASS: TestEXPIRE/TEST(GT):_Set_the_expiration_only_if_the_new_expiration_time_is_greater_than_the_current_one (0.00s)
    --- PASS: TestEXPIRE/TEST(LT):_Set_the_expiration_only_if_the_new_expiration_time_is_less_than_the_current_one (0.00s)
    --- PASS: TestEXPIRE/TEST(LT):_Set_the_expiration_only_if_the_new_expiration_time_is_less_than_the_current_one#01 (0.00s)
    --- PASS: TestEXPIRE/TEST(NX_+_LT/GT) (0.00s)
    --- PASS: TestEXPIRE/TEST(XX_+_LT/GT) (0.00s)
    --- PASS: TestEXPIRE/Test_if_value_is_nil_after_expiration (2.00s)
    --- PASS: TestEXPIRE/Test_if_value_is_nil_after_expiration#01 (2.00s)
    --- PASS: TestEXPIRE/Invalid_Command_Test (0.00s)
    --- PASS: TestEXPIRE/EXPIRE_with_no_keys_or_arguments (0.00s)
PASS
ok      github.com/dicedb/dice/tests/commands/ironhawk  7.056s
testing: warning: no tests to run
PASS
ok      github.com/dicedb/dice/tests/server     1.012s [no tests to run]
abhijeet@abhijeet:/mnt/c/code/dice$ TEST_FUNC="^TestDEL$" make test-one
CGO_ENABLED=1 go test -v -race -count=1 --run ^TestDEL$ ./tests/...
=== RUN   TestDEL
=== RUN   TestDEL/DEL_with_set_key
=== RUN   TestDEL/DEL_multiple_keys
=== RUN   TestDEL/DEL_with_key_not_set
=== RUN   TestDEL/DEL_with_no_keys_or_arguments
--- PASS: TestDEL (0.01s)
    --- PASS: TestDEL/DEL_with_set_key (0.00s)
    --- PASS: TestDEL/DEL_multiple_keys (0.00s)
    --- PASS: TestDEL/DEL_with_key_not_set (0.00s)
    --- PASS: TestDEL/DEL_with_no_keys_or_arguments (0.00s)
PASS
ok      github.com/dicedb/dice/tests/commands/ironhawk  1.043s
testing: warning: no tests to run
PASS
ok      github.com/dicedb/dice/tests/server     1.013s [no tests to run]
abhijeet@abhijeet:/mnt/c/code/dice$ TEST_FUNC="^TestGET$" make test-one
CGO_ENABLED=1 go test -v -race -count=1 --run ^TestGET$ ./tests/...
=== RUN   TestGET
=== RUN   TestGET/Get_with_expiration
=== RUN   TestGET/Get_without_expiration
=== RUN   TestGET/Get_with_non_existent_key
=== RUN   TestGET/GET_with_no_keys_or_arguments
--- PASS: TestGET (2.01s)
    --- PASS: TestGET/Get_with_expiration (2.00s)
    --- PASS: TestGET/Get_without_expiration (0.00s)
    --- PASS: TestGET/Get_with_non_existent_key (0.00s)
    --- PASS: TestGET/GET_with_no_keys_or_arguments (0.00s)
PASS
ok      github.com/dicedb/dice/tests/commands/ironhawk  3.035s
testing: warning: no tests to run
PASS
ok      github.com/dicedb/dice/tests/server     1.013s [no tests to run]
```

### CODE REVIEW

**Comment by arpitbbhayani** [comment]
There are some merge conflicts. I pushed some enhancements. Please refer to https://github.com/DiceDB/dice/blob/master/tests/commands/ironhawk/decr_test.go to see how we write tests.

**Comment by Abhijeetsng97** [comment]
> There are some merge conflicts. I pushed some enhancements. Please refer to https://github.com/DiceDB/dice/blob/master/tests/commands/ironhawk/decr_test.go to see how we write tests.

pushed changes as per flow

File: tests/commands/ironhawk/del_test.go [hunk 1]
```diff
@@ -18,10 +18,11 @@ func TestDel(t *testing.T) {
 			commands: []string{"SET k1 v1", "DEL k1", "GET k1"},
 			expected: []interface{}{"OK", 1, nil},
 		},
+		// TODO: 3rd and 4th commands should be together but delete on multi shard isn't supported as of now
 		{
 			name:     "DEL multiple keys",
-			commands: []string{"SET k1 v1", "SET k2 v2", "DEL k1 k2", "GET k1", "GET k2"},
-			expected: []interface{}{"OK", "OK", 2, nil, nil},
+			commands: []string{"SET k1 v1", "SET k2 v2", "DEL k1", "DEL k2", "GET k1", "GET k2"},
+			expected: []interface{}{"OK", "OK", 1, 1, nil, nil},
```
Comment (arpitbbhayani) [inline tests/commands/ironhawk/del_test.go:25]: these are wrong. the tests should not have been changed, but rather we had to add a multi-shard support for DEL command. I have added this. Pull from the master and you need not make any changes to this test.

File: tests/commands/ironhawk/exists_test.go [hunk 2]
```diff
@@ -18,23 +19,32 @@ func TestExists(t *testing.T) {
 			commands: []string{"SET key value", "EXISTS key", "EXISTS key2"},
 			expected: []interface{}{"OK", 1, 0},
 		},
+		// TODO: expected response should be updated for all exists command once multi shard is implemented
 		{
 			name:     "Test EXISTS command with multiple keys",
 			commands: []string{"SET key value", "SET key2 value2", "EXISTS key key2 key3", "EXISTS key key2 key3 key4", "DEL key", "EXISTS key key2 key3 key4"},
-			expected: []interface{}{"OK", "OK", 2, 2, 1, 1},
+			expected: []interface{}{"OK", "OK", 1, 1, 1, 0},
```
Comment (arpitbbhayani) [inline tests/commands/ironhawk/exists_test.go:26]: unexpected.

File: tests/commands/ironhawk/exists_test.go [hunk 3]
```diff
@@ -18,23 +19,32 @@ func TestExists(t *testing.T) {
...
 			commands: []string{"SET key value ex 1", "EXISTS key", "EXISTS key"},
 			expected: []interface{}{"OK", 1, 0},
 			delay:    []time.Duration{0, 0, 2 * time.Second},
 		},
+		// TODO: expected response should be updated for all exists command once multi shard is implemented
 		{
 			name:     "Test EXISTS with multiple keys and expired key",
 			commands: []string{"SET key value ex 2", "SET key2 value2", "SET key3 value3", "EXISTS key key2 key3", "EXISTS key key2 key3"},
-			expected: []interface{}{"OK", "OK", "OK", 3, 2},
+			expected: []interface{}{"OK", "OK", "OK", 1, 0},
```
Comment (arpitbbhayani) [inline tests/commands/ironhawk/exists_test.go:38]: unexpected

File: tests/commands/ironhawk/exists_test.go [hunk 4]
```diff
@@ -18,23 +19,32 @@ func TestExists(t *testing.T) {
...
 			delay:    []time.Duration{0, 0, 0, 0, 2 * time.Second},
 		},
+		{
+			name:     "EXISTS with no keys or arguments",
+			commands: []string{"EXISTS"},
+			expected: []interface{}{
+				errors.New("wrong number of arguments for 'EXISTS' command"),
+			},
+		},
```
Comment (arpitbbhayani) [inline tests/commands/ironhawk/exists_test.go:47]: Pull from the master and add this test case to `exists_test.go`. EXISTS does not return an error when no arg is passed. It just returns 0. Check the current behaviour and add an apt test.

**Comment by Abhijeetsng97** [comment]
@arpitbbhayani updated as per master
Also GET SET and EXPIRE were making server crash due to no check of num of args.
added those as well

**Comment by arpitbbhayani** [comment]
Merge conflicts :) can you please rebase the changes?

**Comment by Abhijeetsng97** [comment]
> Merge conflicts :) can you please rebase the changes?

yep done

**Comment by arpitbbhayani** [comment]
Thanks for the patch! means a ton.
