### PR TITLE
port FLUSHDB command to IronHawk

### LINKED ISSUE #1454: IronHawk Port: `FLUSHDB` command
We reimplemented the core of the DiceDB engine and re-wrote - the wire protocol, execution engine, and config management. This rewrite helped us gain 32% throughput over our existing benchmark. One of the core principles we focussed on was to make code easy to extend and debug. As an effort, we need to migrate the command from the old engine to IronHawk.

Here are the exact things to be taken care of to migrate the command `FLUSHDB`

1. setup DiceDB server locally from the source - [instructions](https://github.com/dicedb/dice)
2. setup DiceDB CLI locally from the source - [instructions](https://github.com/dicedb/dice)

### Start the DiceDB server with IronHawk engine

```
$ go run main.go --engine ironhawk --log-level debug
```

### Start the DiceDB CLI with the IronHawk engine

```
$ go run main.go --engine ironhawk
```

## Porting the command

1. Find the current implementation of the command, the name of the function will be `evalFLUSHDB`. ex: `evalSET`, `evalGET`, etc. Most of them are present in the `store_eval.go` file.
2. Create a new file `internal/cmd/cmd_flushdb.go` and follow the structure as `cmd_get.go`, `cmd_set.go`, and `cmd_ping.go` files.
3. Reimplement the old `evalFLUSHDB` function into a new file, Make a note of the return values of the new function.
4. If you think the implementation is complex, feel free to simplify
5. Document the code you have written and make sure it adheres to existing standard
6. Add `TODO` in the comment, if you feel there are things that need to be implemented later
7. Cover all possible cases for the command implementation
8. Do not delete the old implementation of the `eval` function

*No need* to write test cases for this new implementation. We will take care of this in one shot later. If the test fails, it is okay.

If you find any other bug while you are implementing it, you can either

1. fix it yourself and submit it in a new PR
2. raise a [GitHub issue](https://github.com/DiceDB/dice/issues)

## Follow the contribution guidelines

These are general guidelines to follow before you submit a patch. Please mark them as done
once you complete them

- [ ] please go through the [CONTRIBUTING](https://github.com/DiceDB/dice/tree/master/CONTRIBUTING) guide
- [ ] follow [LOGGING best practices](https://github.com/DiceDB/dice/blob/master/CONTRIBUTING/logging.md)
- [ ] follow [Golang best practices](https://github.com/DiceDB/dice/blob/master/CONTRIBUTING/go.md)
- [ ] run `make lint` on your local copy of the codebase

### PR DESCRIPTION
**Pull request by manosriram**
Migrate FLUSHDB command to support ironhawk engine.

fixes #1454

### CODE REVIEW

File: internal/cmd/cmd_flushdb.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+	}
+
+	flushType := SYNC
+	if len(c.C.Args) == 1 {
+		flushType = strings.ToUpper(c.C.Args[0])
+	}
+
+	switch flushType {
+	case SYNC, ASYNC:
+		store.ResetStore(s)
```
Comment (arpitbbhayani) [inline internal/cmd/cmd_flushdb.go:48]: Rename the method `ResetStore` to `Reset` across the codebase.

Comment (arpitbbhayani) [inline internal/cmd/cmd_flushdb.go:48]: If the function expects no argument when what is the point of having sync/async here?

File: internal/cmd/cmd_flushdb.go [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+)
+
+const (
+	SYNC  string = "sync"
+	ASYNC string = "async"
+)
+
+var cFLUSHDB = &DiceDBCommand{
+	Name:      "FLUSHDB",
+	HelpShort: "FLUSHDB removes all keys from the currently selected database.",
```
Comment (arpitbbhayani) [inline internal/cmd/cmd_flushdb.go:17]: There is no "selected database", change this to "FLUSHDB deletes all the keys".

File: internal/cmd/cmd_flushdb.go [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+	Eval:      evalFLUSHDB,
+}
+
+func init() {
+	commandRegistry.AddCommand(cFLUSHDB)
+}
+
+// FLUSHDB is used to remove all keys from the currently selected database in a DiceDB instance.
```
Comment (arpitbbhayani) [inline internal/cmd/cmd_flushdb.go:25]: Change this to `FLUSHDB deletes all the keys`

File: internal/cmd/cmd_flushdb.go [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+func evalFLUSHDB(c *Cmd, s *dstore.Store) (*CmdRes, error) {
+	if len(c.C.Args) > 1 {
+		return cmdResNil, errWrongArgumentCount("FLUSHDB")
+	}
+
+	flushType := SYNC
+	if len(c.C.Args) == 1 {
+		flushType = strings.ToUpper(c.C.Args[0])
+	}
+
```
Comment (arpitbbhayani) [inline internal/cmd/cmd_flushdb.go:45]: If the function expects no argument when what is the point of having sync/async here?

**Review by arpitbbhayani — CHANGES_REQUESTED** [review]
