### PR TITLE
fix null value in removing array element and add test for this scenario

### LINKED ISSUE #910: Inconsistent `JSON.FORGET`: Getting null when deleting element from array
## Steps to reproduce
- Create a JSON array in DiceDB.
- Use the JSON.FORGET command to remove an element from the array.
- Observe the resulting array.

Screenshot 2024-09-30 at 10 59 51 PM

Screenshot 2024-09-30 at 10 59 51 PM

## Expected output

The expected output when the above set of commands (maybe when run on Redis)

```
["element1", "element3"]
```

## Observed output

The observed output when the above set of commands when run on DiceDB

```
["element1", null, "element3"]
```

## Expectations for resolution
This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
2. addition of relevant test case to ensure we catch the regression

You can find the tests under the `integration_tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

### PR DESCRIPTION
**Pull request by Dhroov7**
This will fix the issue where, instead of completely removing an element from the array and reindexing, we get `null` when we try to forget the element.

Fixes #910

### CODE REVIEW

**Comment by Dhroov7** [comment]
@lucifercr07 @JyotinderSingh Please review

**Comment by Dhroov7** [comment]
@lucifercr07 @JyotinderSingh Bumping up^

File: internal/eval/eval.go [hunk 1]
```diff
@@ -915,7 +914,16 @@ func evalJSONDEL(args []string, store *dstore.Store) []byte {
 		return diceerrors.NewErrWithMessage("invalid JSONPath")
 	}
 	results := expr.Get(jsonData)
-	err = expr.Del(jsonData)
+
+	hasBrackets := strings.Contains(path, "[") && strings.Contains(path, "]")
```
Comment (lucifercr07) [inline internal/eval/eval.go:918]: Please add few cases in test where the key itself has `[`/`]`.
e.g: `JSON.SET data $ '{"key[0]": "value", "array[1]": [10, 20, 30]}'`.

We can validate the behaviour similar to redis.
Like below commands should work
e.g: `JSON.DEL data '["key[0]"]'` etc.

**Review by lucifercr07 — CHANGES_REQUESTED** [review]

File: internal/eval/eval.go (hunk 1 above)
Comment (Dhroov7) [reply internal/eval/eval.go:918]: @lucifercr07 I checked and Redis doesn't allow square brackets in the key itself.

Comment (lucifercr07) [reply internal/eval/eval.go:918]: @Dhroov7 works for me
```
127.0.0.1:6379> JSON.SET data $ '{"key[0]": "value", "array[1]": [10, 20, 30]}'
OK
127.0.0.1:6379> JSON.DEL data '["key[0]"]'
(integer) 1
127.0.0.1:6379> JSON.GET data
"{\"array[1]\":[10,20,30]}"
```

Comment (Dhroov7) [reply internal/eval/eval.go:918]: @lucifercr07 Added the test case, please review

**Review by lucifercr07 — APPROVED** [review]
